// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxoyLU2FrWZhEs9RJC26UO3wGqUbI5r3g',
    appId: '1:71858936026:web:4caa51db912abccf5aede3',
    messagingSenderId: '71858936026',
    projectId: 'shoeshopapp',
    authDomain: 'shoeshopapp.firebaseapp.com',
    databaseURL: 'https://shoeshopapp-default-rtdb.firebaseio.com',
    storageBucket: 'shoeshopapp.appspot.com',
    measurementId: 'G-Z26KJWPL6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEK0vKmDCkBeIVEpTtTdLBhZ-dXN7n-_c',
    appId: '1:71858936026:android:104ef89f0379980c5aede3',
    messagingSenderId: '71858936026',
    projectId: 'shoeshopapp',
    databaseURL: 'https://shoeshopapp-default-rtdb.firebaseio.com',
    storageBucket: 'shoeshopapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ3DwhisCLgaJHqRuskvT5e6BiPyVwWXw',
    appId: '1:71858936026:ios:3caacaed47b8bee45aede3',
    messagingSenderId: '71858936026',
    projectId: 'shoeshopapp',
    databaseURL: 'https://shoeshopapp-default-rtdb.firebaseio.com',
    storageBucket: 'shoeshopapp.appspot.com',
    iosBundleId: 'com.example.midterm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ3DwhisCLgaJHqRuskvT5e6BiPyVwWXw',
    appId: '1:71858936026:ios:3caacaed47b8bee45aede3',
    messagingSenderId: '71858936026',
    projectId: 'shoeshopapp',
    databaseURL: 'https://shoeshopapp-default-rtdb.firebaseio.com',
    storageBucket: 'shoeshopapp.appspot.com',
    iosBundleId: 'com.example.midterm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxoyLU2FrWZhEs9RJC26UO3wGqUbI5r3g',
    appId: '1:71858936026:web:f4852ddb1b9ea41b5aede3',
    messagingSenderId: '71858936026',
    projectId: 'shoeshopapp',
    authDomain: 'shoeshopapp.firebaseapp.com',
    databaseURL: 'https://shoeshopapp-default-rtdb.firebaseio.com',
    storageBucket: 'shoeshopapp.appspot.com',
    measurementId: 'G-8BQTVGJ50Z',
  );
}
